name: Build unitypackage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./Android
      run: ./gradlew build
    - name: Get packaging files
      working-directory: ./Unity/
      run: |
        find Assets/NativeToolkit -type d -exec echo {}.meta \; > meta_list
        find Assets/Plugins -type d -exec echo {}.meta \; >> meta_list
        find Assets/NativeToolkit -type f -name \*.meta >> meta_list
        find Assets/Plugins -type f -name \*.meta >> meta_list
        awk '!seen[$0]++' meta_list > meta_list
    - name: create-unitypackage
      uses: pCYSl5EDgo/create-unitypackage@v1
      with:
        package-path: ./unity-native-toolkit.unitypackage
        include-files: ./Unity/meta_list
        project-folder: ./Unity
    - uses: actions/upload-artifact@v2
      with:
        path: ./unity-native-toolkit.unitypackage
        if-no-files-found: error
